name: Move Bible drafts

on:
  push:
    branches: [ main ]

jobs:
  move-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run move script
        run: bash move_drafts.sh

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Déplacement automatique des fichiers Bible" || echo "Rien à committer"
          git push
